---
- name: Install selinux-pythion lib
  yum: name=libselinux-python

- command: /usr/bin/test -e /etc/selinux/config
  register: selinux_installed
  ignore_errors: yes

- name: Disable SELinux
  selinux: state=disabled
  when: selinux_installed.rc == 0
  register: selinux
  ignore_errors: yes

- name: reboot the servers
  command: /sbin/shutdown -r now
  when: selinux.changed
  ignore_errors: yes