---
- name: Clone rbenv repository
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv version=v0.4.0

- name: Clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build version=v20140517

- name: Add rbenv to PATH
  lineinfile: dest=~/.bashrc line="export PATH=\"$HOME/.rbenv/bin:$PATH\""

- name: Enable rbenv shims and autocompletion
  lineinfile: dest=~/.bashrc line="eval \"$(rbenv init -)\""

- name: Check if ruby version is already installed
  shell: rbenv versions | grep {{ ruby_version }}
  register: ruby_installed
  changed_when: False
  ignore_errors: yes

- name: Install ruby version
  shell: rbenv install {{ ruby_version }}
  when: ruby_installed|failed

- name: Check if {{ ruby_version }} is the global ruby version
  shell: rbenv global
  register: ruby_global
  changed_when: False

- name: Set global ruby version
  shell: rbenv global {{ ruby_version }}
  when: ruby_global.stdout != ruby_version

- name: Check for Bundler
  shell: gem list bundler -v 1.6.2 -i
  register: bundler_installed
  changed_when: False
  ignore_errors: yes

- name: Intall Bundler
  shell: gem install bundler -v 1.6.2
  when: bundler_installed.stdout == "false"

- name: Rehash
  shell: rbenv rehash
  changed_when: False