---
- name: Install basic dependencies
  sudo: yes
  yum: name={{ item }} enablerepo=epel
  with_items:
    - wget-1.12
    - nano-2.0.9
    - htop-1.0.3
    - screen-4.0.3
    - git-1.7.1
    - nodejs-0.10.29
    - npm-1.3.6

- name: Install client build dependencies
  sudo: yes
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - gulp